# Role-based skills data for training
ROLE_SKILLS = {
    "Data Analyst": {
        "technical_skills": [
            "SQL", "Python", "R", "Excel", "Tableau", "Power BI", "Statistics", 
            "Data Visualization", "Pandas", "NumPy", "Matplotlib", "Seaborn",
            "Statistical Analysis", "Data Cleaning", "Data Mining", "Business Intelligence",
            "Google Analytics", "SPSS", "SAS", "Looker", "QlikSense", "Apache Spark",
            "Hadoop", "BigQuery", "Redshift", "Snowflake", "Data Warehousing", 
            "ETL Processes", "Data Modeling", "Database Design", "MySQL", "PostgreSQL",
            "MongoDB", "Oracle", "Data Governance", "Data Quality", "A/B Testing",
            "Regression Analysis", "Hypothesis Testing", "Predictive Modeling", 
            "Machine Learning", "Forecasting", "Dashboard Design", "KPI Development",
            "Data Interpretation", "Report Generation", "Data Storytelling"
        ],
        "soft_skills": [
            "Analytical Thinking", "Problem Solving", "Attention to Detail", 
            "Communication", "Critical Thinking", "Decision Making", "Time Management",
            "Teamwork", "Adaptability", "Presentation Skills", "Business Acumen",
            "Curiosity", "Data-Driven Mindset", "Organizational Skills", "Patience",
            "Logical Reasoning", "Research Skills", "Documentation", "Collaboration",
            "Continuous Learning", "Stakeholder Management", "Requirements Gathering",
            "Process Improvement", "Risk Assessment", "Strategic Planning"
        ]
    },
    "Software Engineer": {
        "technical_skills": [
            "Java", "Python", "JavaScript", "C++", "C#", "HTML", "CSS", "SQL",
            "React", "Angular", "Vue.js", "Node.js", "Express", "Django", "Flask",
            "Spring", "Hibernate", "RESTful APIs", "Microservices", "Git", "Docker",
            "Kubernetes", "AWS", "Azure", "GCP", "Linux", "Bash", "Shell Scripting",
            "MongoDB", "PostgreSQL", "MySQL", "Redis", "Jenkins", "CI/CD",
            "TypeScript", "Next.js", "NestJS", "GraphQL", "Redux", "Webpack", 
            "Vite", "Tailwind CSS", "SASS", "Bootstrap", "jQuery", "PHP", "Ruby",
            "Go", "Rust", "Swift", "Kotlin", "Flutter", "React Native", "Xamarin",
            "Postman", "Swagger", "OAuth", "JWT", "WebSockets", "Serverless",
            "Lambda", "EC2", "S3", "CloudFormation", "Terraform", "Ansible",
            "Prometheus", "Grafana", "ELK Stack", "Nginx", "Apache", "Tomcat",
            "JIRA", "Confluence", "Agile", "Scrum", "Test-Driven Development",
            "Unit Testing", "Integration Testing", "End-to-End Testing", "Selenium",
            "Jest", "Mocha", "Cypress", "Performance Optimization", "Debugging",
            "Code Review", "Refactoring", "Design Patterns", "SOLID Principles",
            "Object-Oriented Programming", "Functional Programming", "System Design",
            "Database Optimization", "Caching", "Load Balancing", "Security Best Practices"
        ],
        "soft_skills": [
            "Problem Solving", "Communication", "Teamwork", "Adaptability", 
            "Time Management", "Critical Thinking", "Leadership", "Attention to Detail",
            "Creativity", "Collaboration", "Mentoring", "Empathy", "Patience",
            "Active Listening", "Conflict Resolution", "Negotiation", "Decision Making",
            "Accountability", "Resilience", "Continuous Learning", "Documentation",
            "Project Management", "Stakeholder Management", "Requirements Analysis",
            "User-Centric Design", "Quality Assurance", "Risk Management", 
            "Strategic Thinking", "Innovation", "Customer Focus", "Feedback Reception"
        ]
    },
    "ML Engineer": {
        "technical_skills": [
            "Python", "TensorFlow", "PyTorch", "Scikit-learn", "Keras", "Pandas", 
            "NumPy", "Matplotlib", "Seaborn", "Jupyter", "SQL", "R", "Statistics",
            "Deep Learning", "Neural Networks", "Computer Vision", "NLP", "Reinforcement Learning",
            "Data Preprocessing", "Feature Engineering", "Model Deployment", "MLOps",
            "Docker", "Kubernetes", "AWS SageMaker", "Google AI Platform", "Azure ML",
            "Spark", "Hadoop", "Git", "MLflow", "Kubeflow", "Airflow", "FastAPI",
            "Flask", "Django", "RESTful APIs", "GraphQL", "CI/CD", "Jenkins",
            "GitHub Actions", "GitLab CI", "Prometheus", "Grafana", "Elasticsearch",
            "Logstash", "Kibana", "Streamlit", "Gradio", "Hugging Face Transformers",
            "BERT", "GPT", "RoBERTa", "XGBoost", "LightGBM", "CatBoost", 
            "Random Forest", "SVM", "Decision Trees", "Ensemble Methods", 
            "Hyperparameter Tuning", "Cross-Validation", "Model Evaluation",
            "Confusion Matrix", "ROC Curve", "AUC", "Precision", "Recall", 
            "F1-Score", "Overfitting", "Underfitting", "Regularization", 
            "Feature Selection", "Dimensionality Reduction", "PCA", "t-SNE",
            "Clustering", "K-Means", "DBSCAN", "Hierarchical Clustering",
            "Time Series Analysis", "ARIMA", "LSTM", "GRU", "GANs", "Autoencoders",
            "Transfer Learning", "Fine-Tuning", "Model Compression", "Quantization",
            "Pruning", "Distillation", "Model Serving", "TFServing", "TorchServe",
            "ONNX", "TensorRT", "Model Monitoring", "Drift Detection", "Bias Detection",
            "Experiment Tracking", "Model Registry", "Feature Store", "Pipeline Orchestration",
            "Model Versioning", "A/B Testing", "Statistical Inference", "Bayesian Methods",
            "Optimization Algorithms", "Gradient Descent", "Backpropagation", "Activation Functions",
            "Loss Functions", "Convolutional Neural Networks", "Recurrent Neural Networks",
            "Transformer Models", "Attention Mechanisms", "Embeddings", "Word Vectors",
            "Sequence Models", "Generative Models", "Variational Autoencoders"
        ],
        "soft_skills": [
            "Analytical Thinking", "Problem Solving", "Communication", "Critical Thinking",
            "Attention to Detail", "Curiosity", "Persistence", "Teamwork", "Adaptability",
            "Research Skills", "Experimentation", "Documentation", "Collaboration",
            "Continuous Learning", "Scientific Method", "Hypothesis Formation",
            "Data Interpretation", "Results Presentation", "Stakeholder Management",
            "Requirements Gathering", "Project Planning", "Time Management",
            "Decision Making", "Risk Assessment", "Ethical AI", "Bias Awareness",
            "Privacy Considerations", "Regulatory Compliance", "Innovation", 
            "Creative Problem Solving", "Strategic Thinking", "Leadership", "Mentoring"
        ]
    },
    "Full Stack Developer": {
        "technical_skills": [
            "JavaScript", "HTML", "CSS", "React", "Angular", "Vue.js", "Node.js",
            "Express", "Python", "Django", "Flask", "Java", "Spring", "C#",
            ".NET", "SQL", "MongoDB", "PostgreSQL", "MySQL", "RESTful APIs",
            "Git", "Docker", "AWS", "Azure", "GCP", "Linux", "Bootstrap",
            "Tailwind CSS", "SASS", "Webpack", "NPM", "Jest", "CI/CD",
            "TypeScript", "Next.js", "NestJS", "GraphQL", "Redux", "Vite",
            "jQuery", "PHP", "Ruby on Rails", "Go", "Rust", "Swift", "Kotlin",
            "Flutter", "React Native", "Xamarin", "Postman", "Swagger", "OAuth",
            "JWT", "WebSockets", "Serverless", "Lambda", "EC2", "S3", 
            "CloudFormation", "Terraform", "Ansible", "Prometheus", "Grafana",
            "ELK Stack", "Nginx", "Apache", "Tomcat", "JIRA", "Confluence",
            "Agile", "Scrum", "Test-Driven Development", "Unit Testing", 
            "Integration Testing", "End-to-End Testing", "Selenium", "Mocha", 
            "Cypress", "Performance Optimization", "Debugging", "Code Review",
            "Refactoring", "Design Patterns", "SOLID Principles", "Object-Oriented Programming",
            "Functional Programming", "System Design", "Database Optimization", 
            "Caching", "Load Balancing", "Security Best Practices", "SEO",
            "Accessibility", "Responsive Design", "Progressive Web Apps", 
            "Web Components", "Micro Frontends", "State Management", "Form Handling",
            "Authentication", "Authorization", "Session Management", "Cookies",
            "Local Storage", "Service Workers", "Web Workers", "WebAssembly",
            "WebRTC", "WebGL", "Canvas API", "Geolocation API", "Payment API"
        ],
        "soft_skills": [
            "Problem Solving", "Communication", "Teamwork", "Adaptability",
            "Time Management", "Attention to Detail", "Creativity", "Critical Thinking",
            "Leadership", "Mentoring", "Empathy", "Patience", "Active Listening",
            "Conflict Resolution", "Negotiation", "Decision Making", "Accountability",
            "Resilience", "Continuous Learning", "Documentation", "Project Management",
            "Stakeholder Management", "Requirements Analysis", "User-Centric Design",
            "Quality Assurance", "Risk Management", "Strategic Thinking", "Innovation",
            "Customer Focus", "Feedback Reception", "Cross-Functional Collaboration",
            "Agile Methodologies", "DevOps Culture", "UX Awareness", "Business Acumen"
        ]
    },
    "DevOps Engineer": {
        "technical_skills": [
            "Linux", "Docker", "Kubernetes", "AWS", "Azure", "GCP", "CI/CD",
            "Jenkins", "GitLab CI", "GitHub Actions", "Terraform", "Ansible",
            "Chef", "Puppet", "Bash", "Python", "Shell Scripting", "Monitoring",
            "Prometheus", "Grafana", "ELK Stack", "Nagios", "Splunk", "Nginx",
            "Apache", "SQL", "NoSQL", "Networking", "Security", "Automation",
            "Git", "Maven", "Gradle", "NPM", "Yarn", "Helm", "Istio", 
            "Linkerd", "Vault", "Consul", "Nomad", "Packer", "Vagrant",
            "VirtualBox", "VMware", "OpenStack", "Cloud Foundry", "Heroku",
            "DigitalOcean", "Linode", "Cloudflare", "DNS", "SSL/TLS", 
            "Load Balancers", "CDN", "Firewalls", "IDS/IPS", "SIEM", 
            "Vulnerability Scanning", "Penetration Testing", "Compliance",
            "GDPR", "HIPAA", "SOX", "PCI DSS", "Audit Trails", "Logging",
            "Log Aggregation", "Metrics Collection", "Alerting", "Incident Response",
            "Disaster Recovery", "Backup Strategies", "High Availability",
            "Fault Tolerance", "Scalability", "Performance Tuning", "Cost Optimization",
            "Infrastructure as Code", "Configuration Management", "Orchestration",
            "Containerization", "Microservices", "Service Mesh", "API Gateways",
            "Message Queues", "Kafka", "RabbitMQ", "Redis", "Memcached",
            "Database Replication", "Sharding", "Clustering", "Storage Management",
            "File Systems", "Block Storage", "Object Storage", "NAS", "SAN",
            "Active Directory", "LDAP", "OAuth", "SAML", "PKI", "Encryption"
        ],
        "soft_skills": [
            "Problem Solving", "Communication", "Teamwork", "Adaptability",
            "Attention to Detail", "Time Management", "Critical Thinking", 
            "Collaboration", "Leadership", "Empathy", "Patience", "Active Listening",
            "Conflict Resolution", "Negotiation", "Decision Making", "Accountability",
            "Resilience", "Continuous Learning", "Documentation", "Project Management",
            "Stakeholder Management", "Risk Assessment", "Process Improvement",
            "Change Management", "Vendor Management", "Budget Management",
            "Strategic Planning", "Crisis Management", "Root Cause Analysis",
            "Troubleshooting", "Knowledge Sharing", "Mentoring", "Training",
            "Cross-Functional Collaboration", "Customer Focus", "Quality Assurance",
            "Security Awareness", "Compliance Mindset", "Innovation", "Automation Mindset"
        ]
    },
    "Product Manager": {
        "technical_skills": [
            "Product Lifecycle Management", "Agile", "Scrum", "Jira", "Confluence",
            "Roadmapping", "User Stories", "Wireframing", "Prototyping", "A/B Testing",
            "Analytics", "Google Analytics", "Mixpanel", "SQL", "Excel", "Tableau",
            "Power BI", "Market Research", "Competitive Analysis", "ROI Analysis",
            "User Research", "Customer Interviews", "Surveys", "Usability Testing",
            "Persona Development", "Journey Mapping", "Value Proposition", 
            "Business Model Canvas", "SWOT Analysis", "PEST Analysis", "Porter's Five Forces",
            "Kano Model", "MoSCoW Prioritization", "RICE Scoring", "ICE Scoring",
            "North Star Metric", "KPIs", "OKRs", "Metrics Framework", "Data Analysis",
            "Statistical Analysis", "Funnel Analysis", "Cohort Analysis", "Retention Analysis",
            "Churn Analysis", "LTV Calculation", "CAC Calculation", "ARR", "MRR",
            "Product Discovery", "Requirement Gathering", "Stakeholder Management",
            "Cross-Functional Collaboration", "Go-to-Market Strategy", "Product Launch",
            "Feature Prioritization", "Backlog Management", "Sprint Planning",
            "Release Planning", "Product Vision", "Strategy Development", 
            "Market Positioning", "Pricing Strategy", "Monetization Models",
            "Product Analytics", "Dashboard Creation", "Reporting", "Forecasting",
            "Budget Management", "Resource Allocation", "Risk Management",
            "Change Management", "Innovation Management", "Technology Trends",
            "Digital Transformation", "User Experience", "Customer Success",
            "Sales Enablement", "Marketing Alignment", "Legal Compliance"
        ],
        "soft_skills": [
            "Leadership", "Communication", "Strategic Thinking", "Problem Solving",
            "Decision Making", "Negotiation", "Teamwork", "Adaptability", 
            "Time Management", "Presentation Skills", "Customer Focus",
            "Empathy", "Active Listening", "Influence Without Authority", 
            "Conflict Resolution", "Critical Thinking", "Analytical Skills",
            "Creativity", "Innovation", "Visionary Thinking", "Execution",
            "Accountability", "Resilience", "Continuous Learning", "Documentation",
            "Project Management", "Stakeholder Management", "Requirements Analysis",
            "User-Centric Design", "Business Acumen", "Financial Literacy",
            "Market Awareness", "Competitive Intelligence", "Risk Assessment",
            "Process Improvement", "Change Management", "Cultural Awareness",
            "Diversity and Inclusion", "Ethical Decision Making", "Feedback Reception",
            "Mentoring", "Coaching", "Public Speaking", "Writing Skills",
            "Cross-Cultural Communication", "Emotional Intelligence", "Persuasion"
        ]
    },
    "UI/UX Designer": {
        "technical_skills": [
            "Figma", "Sketch", "Adobe XD", "Photoshop", "Illustrator", "InVision",
            "HTML", "CSS", "JavaScript", "Prototyping", "Wireframing", "User Research",
            "Usability Testing", "Information Architecture", "Interaction Design",
            "Visual Design", "Responsive Design", "Mobile Design", "Design Systems",
            "Atomic Design", "Design Thinking", "User-Centered Design", 
            "Human-Computer Interaction", "Cognitive Psychology", "Accessibility",
            "WCAG", "ARIA", "Color Theory", "Typography", "Grid Systems",
            "Layout Design", "Icon Design", "Motion Design", "Animation", 
            "Microinteractions", "Storytelling", "Narrative Design", "Brand Identity",
            "Logo Design", "Illustration", "Photography", "3D Design", 
            "VR/AR Design", "Voice User Interface", "Conversational Design",
            "Service Design", "Journey Mapping", "Persona Development", 
            "Empathy Mapping", "User Testing", "A/B Testing", "Multivariate Testing",
            "Heatmaps", "Eye Tracking", "Surveys", "Interviews", "Focus Groups",
            "Card Sorting", "Tree Testing", "First Click Testing", "Five-Second Testing",
            "Cognitive Walkthrough", "Heuristic Evaluation", "Nielsen's Heuristics",
            "Gestalt Principles", "Fitts's Law", "Hick's Law", "Miller's Law",
            "Jakob's Law", "Von Restorff Effect", "Serial Position Effect",
            "Front-End Development", "React", "Vue.js", "Angular", "Bootstrap",
            "Tailwind CSS", "SASS", "LESS", "Web Accessibility", "SEO", 
            "Performance Optimization", "Cross-Browser Compatibility", 
            "Responsive Frameworks", "Design Tokens", "Component Libraries",
            "Style Guides", "Pattern Libraries", "Design Handoff", "Zeplin",
            "Avocode", "Abstract", "Zeroheight", "Storybook", "Framer", 
            "Principle", "Origami Studio", "Axure", "Balsamiq", "Marvel", 
            "Proto.io", "Justinmind", "Mockplus", "Pidoco", "UXPin"
        ],
        "soft_skills": [
            "Creativity", "Communication", "Empathy", "Problem Solving", 
            "Attention to Detail", "Collaboration", "Adaptability", "Critical Thinking",
            "Presentation Skills", "User Advocacy", "Active Listening", 
            "Influence Without Authority", "Conflict Resolution", "Negotiation",
            "Decision Making", "Accountability", "Resilience", "Continuous Learning",
            "Documentation", "Project Management", "Stakeholder Management",
            "Requirements Analysis", "Business Acumen", "Market Awareness",
            "Cultural Awareness", "Diversity and Inclusion", "Ethical Design",
            "Privacy Considerations", "Feedback Reception", "Mentoring", 
            "Coaching", "Public Speaking", "Writing Skills", "Cross-Cultural Communication",
            "Emotional Intelligence", "Persuasion", "Curiosity", "Patience",
            "Open-Mindedness", "Flexibility", "Self-Awareness", "Self-Regulation",
            "Motivation", "Social Skills", "Systems Thinking", "Strategic Thinking",
            "Innovation", "Visionary Thinking", "Execution", "Quality Assurance"
        ]
    },
    "Cybersecurity Analyst": {
        "technical_skills": [
            "Network Security", "SIEM", "Firewalls", "IDS/IPS", "Vulnerability Assessment",
            "Penetration Testing", "Incident Response", "Risk Management", "Compliance",
            "Encryption", "Authentication", "Authorization", "Security Audits",
            "Python", "Bash", "Linux", "Windows", "Security Tools", "SOC",
            "Threat Intelligence", "Malware Analysis", "Forensics", "Intrusion Detection",
            "Intrusion Prevention", "Network Monitoring", "Log Analysis", 
            "Security Information Management", "Security Event Management",
            "Security Orchestration", "Threat Hunting", "Digital Forensics",
            "Incident Handling", "Disaster Recovery", "Business Continuity",
            "Identity Management", "Access Control", "Privileged Access Management",
            "Multi-Factor Authentication", "Single Sign-On", "Federation",
            "Public Key Infrastructure", "Digital Certificates", "SSL/TLS",
            "IPSec", "VPN", "Wireless Security", "Mobile Device Security",
            "Cloud Security", "Container Security", "Kubernetes Security",
            "Application Security", "Web Application Firewalls", "Secure Coding",
            "OWASP Top 10", "CWE", "CVE", "CVSS", "NIST Framework", 
            "ISO 27001", "SOC 2", "HIPAA", "GDPR", "PCI DSS", "FERPA",
            "FISMA", "CMMC", "CIS Controls", "MITRE ATT&CK", "STIX", "TAXII",
            "YARA", "Snort", "Suricata", "Bro/Zeek", "OSSEC", "Wazuh",
            "Splunk", "ELK Stack", "ArcSight", "QRadar", "AlienVault", 
            "LogRhythm", "RSA NetWitness", "IBM QRadar", "McAfee SIEM",
            "SolarWinds LEM", "Graylog", "Security Onion", "Kali Linux",
            "Metasploit", "Nmap", "Wireshark", "Burp Suite", "Nessus",
            "OpenVAS", "Qualys", "Acunetix", "Nikto", "SQLMap", "John the Ripper",
            "Hashcat", "Aircrack-ng", "Hydra", "Maltego", "Recon-ng",
            "Social-Engineer Toolkit", "Cobalt Strike", "Empire", "Covenant",
            "BloodHound", "Mimikatz", "PowerSploit", "Responder", "Impacket",
            "Sliver", "Mythic", "Red Canary", "CrowdStrike", "Carbon Black",
            "SentinelOne", "Cylance", "FireEye", "Palo Alto", "Fortinet",
            "Check Point", "Cisco", "Juniper", "Pulse Secure", "Zscaler",
            "Symantec", "McAfee", "Trend Micro", "Sophos", "Bitdefender"
        ],
        "soft_skills": [
            "Analytical Thinking", "Attention to Detail", "Problem Solving",
            "Communication", "Critical Thinking", "Ethics", "Adaptability",
            "Teamwork", "Decision Making", "Empathy", "Patience", "Active Listening",
            "Conflict Resolution", "Negotiation", "Accountability", "Resilience",
            "Continuous Learning", "Documentation", "Project Management",
            "Stakeholder Management", "Risk Assessment", "Process Improvement",
            "Change Management", "Vendor Management", "Budget Management",
            "Strategic Planning", "Crisis Management", "Root Cause Analysis",
            "Troubleshooting", "Knowledge Sharing", "Mentoring", "Training",
            "Cross-Functional Collaboration", "Customer Focus", "Quality Assurance",
            "Security Awareness", "Compliance Mindset", "Innovation", 
            "Research Skills", "Investigation", "Deduction", "Pattern Recognition",
            "Threat Modeling", "Scenario Planning", "Business Continuity Planning",
            "Disaster Recovery Planning", "Incident Response Planning", 
            "Security Architecture", "Policy Development", "Standards Development",
            "Regulatory Compliance", "Legal Requirements", "Privacy Protection",
            "Data Protection", "Intellectual Property", "Confidentiality",
            "Integrity", "Availability", "Non-Repudiation", "Authentication",
            "Authorization", "Accounting", "Auditing", "Forensics Readiness"
        ]
    }
}